 
DECLARE @CUSTOMERID AS INT
DECLARE @ITEMID AS INT
DECLARE @UNITPRICE AS FLOAT
SELECT TOP 1 @CUSTOMERID =ID FROM LAB03_CUSTOMERS ORDER BY NEWID()
SELECT TOP 1 @ITEMID =ID,@UNITPRICE =UNITPRICE FROM LAB03_ITEMS  ORDER BY NEWID()


DECLARE @DATE AS DATETIME
DECLARE @RAND AS INT
DECLARE @AMOUNT AS INT
DECLARE @LINETOTAL AS FLOAT
SET @RAND =RAND()*365
SET @DATE =DATEADD(DAY,@RAND,'2021-01-01')
SET @DATE =DATEADD(HOUR,8,@DATE)
SET @RAND =RAND()*12*60*60
SET @DATE =DATEADD(SECOND,@RAND,@DATE)
SET @AMOUNT =1+(RAND()*19)
SET @LINETOTAL =@AMOUNT*@UNITPRICE

INSERT INTO LAB03_SALES (CUSTOMERID,ITEMID,DATE_,AMOUNT,UNITPRICE,LINETOTAL)
VALUES (@CUSTOMERID,@ITEMID,@DATE,@AMOUNT,@UNITPRICE,@LINETOTAL)

SELECT * FROM LAB03_SALES

SELECT 
C.NAMESURNAME,I.ITEMNAME,S.*
FROM LAB03_SALES S
JOIN LAB03_ITEMS I ON I.ID=S.ITEMID 
JOIN LAB03_CUSTOMERS C ON C.ID=S.CUSTOMERID