DECLARE @CITY AS VARCHAR(200)='ÝZMÝR-BURSA-ANKARA-ÝSTANBUL-TRABZON'

SELECT 
	CITY,SUM(AMOUNT) TOTALAMOUNT,SUM(TOTALPRICE) TOTALSALE
FROM LAB05
WHERE CITY IN (SELECT  value  FROM string_split(@CITY,'-'))
GROUP BY CITY 