CREATE PROC SP_GETPLATES
@BRAND AS VARCHAR(100),
@BEGDATE AS DATE,
@ENDDATE AS DATE
AS
SELECT * FROM LAB_PLATES 
WHERE 
BRAND =@BRAND
AND LICENCEDATE BETWEEN @BEGDATE AND @ENDDATE

EXEC SP_GETPLATES 'Audi','20100101','20190101'