ALTER PROC SP_SALES
@BEGDATE AS DATE,
@ENDDATE AS DATE,
@CITIES AS VARCHAR(200)
AS

DECLARE @RESULT AS VARCHAR(1000)
SET @RESULT ='BEGDATE:'+CONVERT(varchar,@BEGDATE,104)
SET @RESULT =@RESULT+CHAR(13)
SET @RESULT =@RESULT+'ENDDATE:'+CONVERT(varchar,@ENDDATE,104)
SET @RESULT =@RESULT+CHAR(13)
SET @RESULT =@RESULT+'CITIES:'+@CITIES

PRINT @RESULT 
SELECT @RESULT AS PARAMETERS

SELECT 
CATEGORY1 CATEGORY,SUM(TOTALPRICE) TOTALSALE
FROM LAB_SALES
WHERE DATE_ BETWEEN @BEGDATE AND @ENDDATE
AND CITY IN (SELECT VALUE FROM string_split(@CITIES,','))
GROUP BY CATEGORY1
ORDER BY 2 DESC 

EXEC SP_SALES @BEGDATE='20190516',@ENDDATE='20190601',
@CITIES='ÝSTANBUL,BURSA,ANKARA,EDÝRNE'