ALTER PROC SP_GET_TERROR_DATA
@GNAME AS VARCHAR(100),
@BEGDATE AS DATE,
@ENDDATE AS DATE,
@COUNTRY AS VARCHAR(100)
AS
 
SELECT YEAR(DATE_) YEAR_,COUNTRY_TXT,COUNT(*) EVENTCOUNT
FROM LAB_GLOBALTERROR
WHERE GNAME=@GNAME
AND DATE_ BETWEEN @BEGDATE AND @ENDDATE
AND COUNTRY_TXT LIKE @COUNTRY
GROUP BY YEAR(DATE_),COUNTRY_TXT
ORDER BY 1
 

EXEC SP_GET_TERROR_DATA
@GNAME ='Ýrlanda Cumhuriyet Ordusu (IRA)',
@BEGDATE='19900101',
@ENDDATE ='20160101',
@COUNTRY ='%'
