ALTER PROC SP_LOGIN
@USERNAME AS VARCHAR(100)=NULL,
@EMAIL AS VARCHAR(100)=NULL,
@PASSWORD AS VARCHAR(50),
@IPADDRESS AS VARCHAR(50)
AS
DECLARE @USERID AS INT
DECLARE @LOGINTYPE AS VARCHAR(100)


IF @USERNAME IS NOT NULL
BEGIN
	SELECT @USERID =ID FROM LAB_USER WHERE USERNAME_=@USERNAME AND PASSWORD_ =@PASSWORD
	IF @USERID >0
	BEGIN
		SET @LOGINTYPE ='GÝRÝÞ BAÞARILI'
		INSERT INTO LAB_USERLOGIN_LOG (USERID,USERNAME,LOGINTYPE,IPADDRESS,DATE_)
		VALUES (@USERID,@USERNAME,@LOGINTYPE,@IPADDRESS,GETDATE())
	END
	ELSE
	BEGIN
		SET @LOGINTYPE ='GÝRÝÞ BAÞARISIZ'
		INSERT INTO LAB_USERLOGIN_LOG (USERID,USERNAME,LOGINTYPE,IPADDRESS,DATE_)
		VALUES (@USERID,@USERNAME,@LOGINTYPE,@IPADDRESS,GETDATE())
	END
	
SELECT * FROM LAB_USER WHERE USERNAME_=@USERNAME AND PASSWORD_ =@PASSWORD
END

IF @EMAIL IS NOT NULL
BEGIN
	SELECT @USERID =ID FROM LAB_USER WHERE EMAIL=@EMAIL AND PASSWORD_ =@PASSWORD
	IF @USERID >0
	BEGIN
		SET @LOGINTYPE ='GÝRÝÞ BAÞARILI'
		INSERT INTO LAB_USERLOGIN_LOG (USERID,USERNAME,LOGINTYPE,IPADDRESS,DATE_)
		VALUES (@USERID,@EMAIL,@LOGINTYPE,@IPADDRESS,GETDATE())
	END
	ELSE
	BEGIN
		SET @LOGINTYPE ='GÝRÝÞ BAÞARISIZ'
		INSERT INTO LAB_USERLOGIN_LOG (USERID,USERNAME,LOGINTYPE,IPADDRESS,DATE_)
		VALUES (@USERID,@EMAIL,@LOGINTYPE,@IPADDRESS,GETDATE())
	END
	
SELECT * FROM LAB_USER WHERE EMAIL =@EMAIL AND PASSWORD_ =@PASSWORD
END


EXEC SP_LOGIN  @USERNAME='N_OZSIMITCI',@PASSWORD='4598751',@IPADDRESS='136.58.96.214'
EXEC SP_LOGIN  @EMAIL='N_OZSIMITCI@sqlegitimbtk.com',@PASSWORD='4598751',@IPADDRESS='136.58.96.214'
