SELECT 
CATEGORY1+'>'+CATEGORY2+'>'+CATEGORY3+'>'+CATEGORY4 CATEGORY,
SUM(TOTALPRICE) TOTALSALE,
CONVERT(INT,SUM(TOTALPRICE)) TOTALSALE_INT,
CEILING(SUM(TOTALPRICE)) TOTALSALE_CEILING,
FLOOR(SUM(TOTALPRICE)) TOTALSALE_FLOOR,
ROUND(SUM(TOTALPRICE),0) TOTALSALE_ROUND
FROM LAB03

GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
ORDER BY 1