DECLARE @K AS INT=0
WHILE @K<10000
BEGIN
--TRUNCATE TABLE LAB05_SALES 
DECLARE @FICHENO AS VARCHAR(20)
DECLARE @DATE_ AS DATETIME
DECLARE @ITEMCODE VARCHAR(20) 
DECLARE @ITEMNAME VARCHAR(100)
DECLARE @BRAND VARCHAR(100)
DECLARE @CATEGORY1 VARCHAR(100)
DECLARE @CATEGORY2 VARCHAR(100)
DECLARE @CATEGORY3 VARCHAR(100)
DECLARE @CATEGORY4 VARCHAR(100)
DECLARE @AMOUNT INT
DECLARE @PRICE FLOAT
DECLARE @TOTALPRICE FLOAT
DECLARE @CUSTOMERCODE VARCHAR(100) 
DECLARE @CUSTOMERNAME VARCHAR(100)
DECLARE @CUSTOMERBIRHTDATE DATE
DECLARE @CUSTOMERGENDER CHAR(1)
DECLARE @BRANCH VARCHAR(100)
DECLARE @CITY  VARCHAR(100)
DECLARE @DISTRICT VARCHAR(100)
DECLARE @REGION VARCHAR(100)
DECLARE @RANDID AS INT
DECLARE @ITEMCOUNT AS INT


SELECT @FICHENO =CONVERT(varchar,CONVERT(INT,MAX(FICHENO))+1) FROM LAB05_SALES 
SET @FICHENO =ISNULL(@FICHENO,'1')

SET @FICHENO =REPLICATE('0',10-LEN(@FICHENO))+@FICHENO

SET @RANDID=365*RAND()
SET @DATE_ =DATEADD(DAY,@RANDID,'2021-01-01')
SET @DATE_=DATEADD(HOUR,8,@DATE_)
SET @RANDID =RAND()*14*60*60
SET @DATE_=DATEADD(SECOND,@RANDID,@DATE_)

SET @RANDID=RAND()*10037
SELECT @CITY=CITYNAME,@REGION =REGION FROM LAB05_CITIES WHERE @RANDID BETWEEN RANDOMBEG AND RANDOMEND

SELECT TOP 1 
@CUSTOMERCODE=ID,@CUSTOMERNAME=NAMESURNAME,@CUSTOMERBIRHTDATE =BIRTHDATE,@CUSTOMERGENDER=GENDER,@DISTRICT=TOWN
FROM LAB05_CUSTOMERS WHERE CITY=@CITY ORDER BY NEWID()
SET @BRANCH =@CITY 

SET @ITEMCOUNT =1+(RAND()*9)
DECLARE @I AS INT=0
WHILE @I<@ITEMCOUNT
BEGIN
	SET @RANDID =1+RAND()*28066
	SELECT 
	 @ITEMCODE=ITEMCODE, @ITEMNAME=ITEMNAME	,@BRAND= BRAND,@CATEGORY1= CATEGORY1,@CATEGORY2= CATEGORY2,@CATEGORY3= CATEGORY3,@CATEGORY4= CATEGORY4,@PRICE =SALEPRICE
	FROM LAB05_ITEMS  WHERE ID=@RANDID 

	SET @AMOUNT =1+(RAND()*9)

	SET @PRICE =(@PRICE*0.75)*(1+RAND()*0.5)
	SET @TOTALPRICE=@AMOUNT*@PRICE 


	--SELECT  @FICHENO, @DATE_, @ITEMCODE, @ITEMNAME, @BRAND,@CATEGORY1, @CATEGORY2, @CATEGORY3, @CATEGORY4, @AMOUNT, @PRICE ,@TOTALPRICE,@CITY,
	--@CUSTOMERCODE, @CUSTOMERNAME, @CUSTOMERBIRHTDATE, @CUSTOMERGENDER, @BRANCH, @CITY, @DISTRICT, @REGION
	INSERT INTO LAB05_SALES
	( FICHENO, DATE_, ITEMCODE, ITEMNAME, BRAND, CATEGORY1, CATEGORY2, CATEGORY3, CATEGORY4, AMOUNT, PRICE, 
	TOTALPRICE, CUSTOMERCODE, CUSTOMERNAME, CUSTOMERBIRHTDATE, CUSTOMERGENDER, BRANCH, CITY, DISTRICT, REGION)
	VALUES 
	(@FICHENO, @DATE_, @ITEMCODE, @ITEMNAME, @BRAND, @CATEGORY1, @CATEGORY2, @CATEGORY3, @CATEGORY4, @AMOUNT, @PRICE, @TOTALPRICE, @CUSTOMERCODE, @CUSTOMERNAME, @CUSTOMERBIRHTDATE, @CUSTOMERGENDER, @BRANCH, @CITY, @DISTRICT, @REGION)
SET @I=@I+1 
END


SET @K=@K+1
END

SELECT * FROM LAB05_SALES 