TRUNCATE TABLE LAB02_LOG
UPDATE LAB02_DEVICES SET CURRENTVALUE =0

DECLARE @I AS INT=1
WHILE @I<=100
BEGIN
DECLARE @DEVICEID AS INT=@I
DECLARE @DATE AS DATETIME ='2022-08-027 07:30:00'
	WHILE @DATE<='2022-08-027 17:30:00'
	BEGIN
		DECLARE @CURRENTVALUE AS FLOAT
		SELECT @CURRENTVALUE =CURRENTVALUE FROM LAB02_DEVICES WHERE ID=@DEVICEID
		IF @CURRENTVALUE =0
		BEGIN
			SET @CURRENTVALUE =18
		END
		DECLARE @NEWVALUE AS FLOAT
		SET @NEWVALUE =ROUND(@CURRENTVALUE-0.5+RAND(),2)
		UPDATE LAB02_DEVICES SET CURRENTVALUE =@NEWVALUE WHERE ID=@DEVICEID
		INSERT INTO LAB02_LOG (DEVICEID,DATE_,VALUE_) VALUES (@DEVICEID,@DATE,@NEWVALUE)
	SET @DATE=DATEADD(SECOND,30,@DATE)
	END
SET @I=@I+1 
END

 SELECT * FROM LAB02_DEVICES 
SELECT * FROM LAB02_LOG
 