SELECT * FROM LAB01

TRUNCATE TABLE LAB01

DECLARE @I AS INT=1
WHILE @I<=100
BEGIN
	DECLARE @DEVICENAME AS VARCHAR(100)
	SET @DEVICENAME ='THERMOMETER-'+REPLICATE('0',4-LEN(@I))+CONVERT(VARCHAR,@I)
	DECLARE @CURRENTVALUE AS FLOAT
	SET @CURRENTVALUE =ROUND(18+RAND()*5,2)
	INSERT INTO LAB01 (DEVICENAME,CURRENTVALUE) VALUES (@DEVICENAME,@CURRENTVALUE)
	--SELECT @DEVICENAME,@CURRENTVALUE
	SET @I=@I+1
END