--INSERT INTO LAB04_PTSLOG (PTSPOINTID,PLATE,DATE_)
--VALUES (1,'06BV3918','2022-08-27 13:04:22')
TRUNCATE TABLE LAB04_PTSLOG
DECLARE @I AS INT=0
WHILE @I<100000
BEGIN
	DECLARE @PLATE AS VARCHAR(20)
	DECLARE @PTSPOINTID AS INT=1
	DECLARE @DATE AS DATETIME='2022-08-27 00:00:00'
	DECLARE @RANDID AS INT
	DECLARE @RANDTIME AS INT
	SET @RANDID=1+RAND()*999999
	SELECT @PLATE=PLATE FROM LAB04_PLATES WHERE ID=@RANDID 

	SET @RANDTIME=RAND()*24*60*60
	SET @DATE =DATEADD(SECOND,@RANDTIME,@DATE)
	SET @RANDTIME=RAND()*1000
	SET @DATE =DATEADD(MS,@RANDTIME,@DATE)
	INSERT INTO LAB04_PTSLOG (PTSPOINTID,PLATE,DATE_)
	VALUES (@PTSPOINTID,@PLATE,@DATE)
	
	SET @I=@I+1
END



SELECT 
P.PTSNAME,L.DATE_,L.PLATE,C.TITLE
FROM LAB04_PTSLOG L
JOIN LAB04_PTSPOINT P ON P.ID=L.PTSPOINTID
JOIN LAB04_PLATES PL ON PL.PLATE =L.PLATE
JOIN LAB04_CARMODELS C ON C.ID=PL.CARID
ORDER BY L.DATE_

SELECT 
DATEPART(HOUR,L.DATE_) HOUR_,COUNT(L.ID) VEHICLECOUNT
FROM LAB04_PTSLOG L
JOIN LAB04_PTSPOINT P ON P.ID=L.PTSPOINTID
JOIN LAB04_PLATES PL ON PL.PLATE =L.PLATE
JOIN LAB04_CARMODELS C ON C.ID=PL.CARID
GROUP BY  DATEPART(HOUR,L.DATE_)
ORDER BY 1
