/*Her bir futbolcunun 
Yaþýný,yaþ grubunu, Futbolcunun puanýný, Kaç kez yedek kadroda çýktýðýný,
Kaç kez asýl kadroda çýktýðýný,Kaç farklý takýmda oynadýðýný,
Toplam kaç maç yaptýðýný,Kaç yýldýr futbol oynadýðýný */

CREATE FUNCTION DBO.GETPLAYERINFO(@PLAYERID AS INT)
RETURNS TABLE
AS
RETURN
(
SELECT PLAYER_API_ID,PLAYER_NAME,
(SELECT TOP 1 TEAM FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID ORDER BY DATE_ DESC) CURRENTTEAM,
DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AGE,
CASE 
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE())<20 THEN '20 DEN KÜÇÜK'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 20 AND 30 THEN '20-30 ARASI'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE()) BETWEEN 31 AND 40 THEN '31-40 ARASI'
	WHEN DATEDIFF(YEAR,BIRTHDATE,GETDATE())>20 THEN '40 TAN BÜYÜK'
END AS AGEGROUP ,
RATING,
(SELECT COUNT(*) FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID AND PLAYERTYPE='REAL') REALCOUNT,
(SELECT COUNT(*) FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID AND PLAYERTYPE='BACKUP') BACKUPCOUNT,
(SELECT COUNT(DISTINCT TEAM) FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID) TEAMCOUNT,
(SELECT COUNT(*) FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID) TOTALMATCHCOUNT,
(SELECT DATEDIFF(YEAR,MIN(DATE_),MAX(DATE_)) FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID) PLAYINGYEAR,
(SELECT  MIN(DATE_) FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID) FIRSTMATCHDATE,
(SELECT  MAX(DATE_) FROM LAB_MATCH_PLAYER WHERE PLAYERID=P.PLAYER_API_ID) LASTTMATCHDATE



FROM LAB_PLAYER P
WHERE P.PLAYER_API_ID=@PLAYERID
)

SELECT INF.* FROM LAB_PLAYER P
CROSS APPLY DBO.GETPLAYERINFO(P.PLAYER_API_ID) INF
ORDER BY INF.RATING DESC 
 
 
 