ALTER LAB09 ADD BIRTHDATE2 DATE
GO
UPDATE LAB09 SET BIRTHDATE2=DATEFROMPARTS(RIGHT(BIRTHDATE,4),SUBSTRING(BIRTHDATE,4,2),LEFT(BIRTHDATE,2))
WHERE ISDATE( RIGHT(BIRTHDATE,4)+'-'+SUBSTRING(BIRTHDATE,4,2)+'-'+LEFT(BIRTHDATE,2))=1
 
 
 

