 
--1.16095532346930783707184
DECLARE @FEMALESALE AS FLOAT
DECLARE @MALESALE AS FLOAT
DECLARE @RATIO AS FLOAT
SELECT @FEMALESALE=SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER='K'
SELECT @MALESALE=SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER='E'
SET @RATIO =@FEMALESALE/@MALESALE

SELECT *,FEMALESALE/MALESALE AS RATIO,
IIF( FEMALESALE/MALESALE>@RATIO,'ORTALAMADAN YÜKSEK', 'ORTALAMADAN DÜÞÜK') AS STATUS_
FROM
(
SELECT DISTINCT CITY ,
	(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER='K' AND CITY=S.CITY) FEMALESALE,
	(SELECT SUM(TOTALPRICE) FROM LAB03 WHERE CUSTOMERGENDER='E' AND CITY=S.CITY) MALESALE
FROM LAB03 S
) T
ORDER BY 1
 
 