DECLARE @PLATE AS VARCHAR(20)='34%'
DECLARE @COLOR AS VARCHAR(20)=''
DECLARE @TITLE AS VARCHAR(100)=''
DECLARE @BRAND AS VARCHAR(20)=''
DECLARE @LICENCEDATE1 AS DATE  
DECLARE @LICENCEDATE2 AS DATE 
 
 

IF @PLATE=''
	SET @PLATE='%'
IF @COLOR=''
	SET @COLOR='%'
IF @TITLE=''
	SET @TITLE='%'
IF @BRAND=''
	SET @BRAND='%'

 

SELECT * FROM LAB01
WHERE PLATE LIKE @PLATE
AND COLOR LIKE @COLOR
AND TITLE LIKE @TITLE
AND BRAND LIKE @BRAND
AND LICENCEDATE BETWEEN ISNULL(@LICENCEDATE1,'20180101') AND ISNULL(@LICENCEDATE2,GETDATE())
