SELECT 
BRAND,
CASE 
	WHEN YEAR(LICENCEDATE)-YEAR_=0 THEN 'AYNI YIL TRAFÝÐE ÇIKMIÞ'
	WHEN YEAR(LICENCEDATE)-YEAR_=1 THEN 'BÝR YIL SONRA TRAFÝÐE ÇIKMIÞ'
	WHEN YEAR(LICENCEDATE)-YEAR_=2 THEN 'ÝKÝ YIL SONRA TRAFÝÐE ÇIKMIÞ'
END AS STATUS_,
COUNT(*) AS COUNT_
FROM LAB02 
GROUP BY BRAND,YEAR(LICENCEDATE)-YEAR_
ORDER BY 1,2

SELECT 
BRAND,
IIF(YEAR(LICENCEDATE)-YEAR_=0,'AYNI YIL TRAFÝÐE ÇIKMIÞ','ÜRETÝM TARÝHÝNDEN SONRAKÝ YILLARDA TRAFÝÐE ÇIKMIÞ') AS STATUS_,
COUNT(*) AS COUNT_
FROM LAB02 
GROUP BY BRAND,IIF(YEAR(LICENCEDATE)-YEAR_=0,'AYNI YIL TRAFÝÐE ÇIKMIÞ','ÜRETÝM TARÝHÝNDEN SONRAKÝ YILLARDA TRAFÝÐE ÇIKMIÞ')
ORDER BY 1,2