--SIPARISNO	TARIH	YIL	GUN	AY	AYNR	KULLANICIADI	ADSOYAD	CINSIYET	EMAIL	TELEFON1	
--ACIKADRES	POSTAKODU	SEHIR	ILCE	URUNKODU	URUNADI	MARKA	KATEGORI1	MIKTAR	BIRIMFIYAT	
--SATIRTOPLAMI


CREATE VIEW VWSATISLAR
AS
SELECT 
O.ID SIPARISNO,O.DATE_ TARIH,YEAR(O.DATE_) YIL, DATENAME(DW,O.DATE_) GUN,
DATENAME(MONTH,O.DATE_) AY,MONTH(O.DATE_) AYNR,
U.USERNAME_ KULLANICIADI,U.NAMESURNAME ADSOYAD,U.GENDER CINSIYET,
U.EMAIL,U.TELNR1 TELEFON1,
A.ADDRESSTEXT ACIKADRES,A.POSTALCODE POSTAKODU,C.CITY SEHIR,T.TOWN ILCE,
I.ITEMCODE URUNKODU,I.ITEMNAME URUNADI,I.BRAND MARKA,I.CATEGORY1 KATEGORU1,OD.AMOUNT MIKTAR,OD.UNITPRICE BIRIMFIYAT,
OD.LINETOTAL SATIRTOPLAMI 
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN USERS U ON U.ID=O.USERID 
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID 
JOIN TOWNS T ON T.ID=A.TOWNID 
JOIN ITEMS I ON I.ID=OD.ITEMID 
