CREATE VIEW VWINVOICEDURATION
AS
SELECT C.CITY SEHIR,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) ORT_HAZIRLIK_SURESI

FROM ORDERS O
JOIN INVOICES I ON I.ORDERID =O.ID 
JOIN ADDRESS A ON A.ID=I.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID 
GROUP BY C.CITY 