alter VIEW VWMONTHLYSALES
AS
SELECT  
CASE 
	WHEN MONTH(DATE_)=1 THEN '01.OCAK'
	WHEN MONTH(DATE_)=2 THEN '02.ÞUBAT'
	WHEN MONTH(DATE_)=3 THEN '03.MART'
	WHEN MONTH(DATE_)=4 THEN '04.NÝSAN'
	WHEN MONTH(DATE_)=5 THEN '05.MAYIS'
	WHEN MONTH(DATE_)=6 THEN '06.HAZÝRAN'
	WHEN MONTH(DATE_)=7 THEN '07.TEMMUZ'
	WHEN MONTH(DATE_)=8 THEN '08.AÐUSTOS'
	WHEN MONTH(DATE_)=9 THEN '09.EYLÜL'
	WHEN MONTH(DATE_)=10 THEN '10.EKÝM'
	WHEN MONTH(DATE_)=11 THEN '11.KASIM'
	WHEN MONTH(DATE_)=12 THEN '12.ARALIK'
END AS MONTHNAME_,
 SUM(TOTALPRICE) TOTALSALE
FROM ORDERS 
GROUP BY MONTH(DATE_)

