CREATE VIEW VWBUGUNDOGANLAR
AS
SELECT 
NAMESURNAME ADSOYAD,
'Sn '+NAMESURNAME+' '+GENDEREXP+'; '+CONVERT(varchar,AGE)+'. yaþýnýzý kutlar, ailenizle birlikte nice mutlu yýllar geçirmenizi dileriz.' MESAJ
FROM 
(
	SELECT 
	NAMESURNAME,GENDER,DATEDIFF(YEAR,BIRTHDATE,GETDATE()) AGE,BIRTHDATE ,
	IIF(GENDER='K','Haným','Bey') GENDEREXP
	FROM USERS 
	WHERE
	DATEPART(MONTH,BIRTHDATE)=DATEPART(MONTH,GETDATE())
	AND DATEPART(DAY,BIRTHDATE)=DATEPART(DAY,GETDATE())
) T